"""
TradingBrain

TB002 - ICT Liquidity Sweep Inversion Constants
"""

from __future__ import annotations

from datetime import time

STRATEGY_ID = "TB002"
STRATEGY_NAME = "ICT Liquidity Sweep Inversion"
STRATEGY_VERSION = "1.0.0"

MARKET_OPEN = time(9, 15)
MARKET_CLOSE = time(15, 30)
DEFAULT_ENTRY_START = time(9, 20)
NO_NEW_ENTRY_AFTER = time(15, 0)

DEFAULT_REQUESTED_RISK = 0.01
HIGH_VOL_REQUESTED_RISK = 0.005
MAX_POSITION_RISK = 0.02

MIN_RISK_REWARD = 1.5
MIN_CONFIDENCE = 0.70
MAX_SETUP_AGE_MINUTES = 240
MAX_HTF_INVERSION_CANDLES = 2

PULLBACK_TIMEFRAMES = ("15m",)
TRIGGER_TIMEFRAMES = ("1m", "5m")
FIRST_TRIM_FRACTION = 0.50

MAX_STRATEGY_DRAWDOWN = 0.10
MAX_DAILY_LOSS = 0.05

LOGGER_NAME = "TB002"
